### PR TITLE
Pull Request #1

### PR DESCRIPTION
**Pull request by john4pius**
This is a request to merge branch build to master branch if TSE approves the project. All work was done on the "build" branch.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @john4pius and @nrqrmz, great job with this project :+1: Our commit messages are descriptive, passed all linter, and validator checks :smile: Great use of HTML semantics. Overall the project looks good. However, we can improve our project by addressing the comments below:
- Kindly add a link to the NYT logo
nyt
- Kindly add the hover effects to the links in ```More in space and Astronomy``` and ```Most popular```
- Let us improve on our CSS code by implementing the DRY rule. ```width: 100%``` appears 10+ times
- We are currently missing the editors pick
ed
ed1

Kindly submit another code review after fixing all the comments :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by nrqrmz** [comment]
I don't want to be credited on this project I reported a situation to student success and I am waiting for a resolution

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @john4pius! :+1:
- You can now merge these changes.
- I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
